// Enumerates shipped profiles, aliases, documentation, and curated examples without development artifacts.
export const RESOURCE_PAYLOAD = Object.freeze([
  { path: "CONTRIBUTING.md", mode: 0o644 },
  { path: "LICENSE", mode: 0o644 },
  { path: "LICENSES/Unicode-3.0.txt", mode: 0o644 },
  { path: "NOTICE", mode: 0o644 },
  { path: "README.md", mode: 0o644 },
  { path: "SECURITY.md", mode: 0o644 },
  { path: "THIRD_PARTY_NOTICES.md", mode: 0o644 },
  { path: "VERSION", mode: 0o644 },
  { path: "config/directives/aliases.u220a", mode: 0o644 },
  { path: "config/images/default.u220i", mode: 0o644 },
  { path: "config/printers/local.u220p", mode: 0o644 },
  { path: "docs/architecture.md", mode: 0o644 },
  { path: "docs/cli-contract.md", mode: 0o644 },
  { path: "docs/job-format.md", mode: 0o644 },
  { path: "docs/live-printing.md", mode: 0o644 },
  { path: "docs/lpd-printing.md", mode: 0o644 },
  { path: "docs/printer-settings.md", mode: 0o644 },
  { path: "docs/printhead-images.md", mode: 0o644 },
  { path: "docs/printing-authorization-rationale.md", mode: 0o644 },
  { path: "docs/printing-policy.md", mode: 0o644 },
  { path: "docs/PROVENANCE.md", mode: 0o644 },
  { path: "docs/raw-tcp-printing.md", mode: 0o644 },
  { path: "docs/spec-sources.md", mode: 0o644 },
  { path: "docs/assets/preview.png", mode: 0o644 },
  { path: "examples/chars.txt", mode: 0o644 },
  { path: "examples/coffee_receipt.u220", mode: 0o644 },
  { path: "examples/example.txt", mode: 0o644 },
  { path: "examples/plain_receipt.u220", mode: 0o644 },
  { path: "examples/type_b_76.u220p", mode: 0o644 },
]);
